# Kaggle Submission

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import pickle
import numpy as np
np.random.seed(42)

## Load in trained model and scaler

In [2]:
!pwd

/Users/davidbickham/dsi/project_2/code

In [3]:
with open('../assets/scaler_1553209257.pkl', 'rb') as f:
    ss = pickle.load(f)
    
with open('../assets/lin_reg.pkl', 'rb') as f:
    lr = pickle.load(f)
    
with open('../assets/columns_1553209257.pkl', 'rb') as f:
    cols = pickle.load(f)

## Load kaggle data

In [4]:
kaggle = pd.read_csv('../data/test.csv', index_col = 'Id',na_values='', keep_default_na=False)

In [5]:
kaggle.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
Id,,,,,,,,,,,,,,,,,,,,,
2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,AllPub,...,0,0,0,NA,NA,NA,0,4,2006,WD
2718,905108090,90,RL,NaN,9662,Pave,NA,IR1,Lvl,AllPub,...,0,0,0,NA,NA,NA,0,8,2006,WD
2414,528218130,60,RL,58.0,17104,Pave,NA,IR1,Lvl,AllPub,...,0,0,0,NA,NA,NA,0,9,2006,New
1989,902207150,30,RM,60.0,8520,Pave,NA,Reg,Lvl,AllPub,...,0,0,0,NA,NA,NA,0,7,2007,WD
625,535105100,20,RL,NaN,9500,Pave,NA,IR1,Lvl,AllPub,...,0,185,0,NA,NA,NA,0,7,2009,WD

## Drop Fields and Handle Case

In [6]:
kaggle.columns = [x.lower().replace(' ','_') for x in kaggle.columns]

In [7]:
kaggle.drop('pid', axis=1,inplace=True)

In [8]:
kaggle.drop('misc_val',axis=1,inplace=True)

## Clean data in same method as training data

In [9]:
kaggle.fillna(
{'mas_vnr_type': 'None'
 ,'mas_vnr_area': 0.0
 ,'bsmt_exposure': 'No'
  ,'bsmt_qual': 'TA'
 ,'bsmt_cond': 'TA'
    ,'bsmtfin_type_1': 'GLQ'
    ,'bsmtfin_type_2': 'Unf'
    ,'garage_finish': 'Unf'
    ,'garage_qual': 'TA'
    ,'garage_cond': 'TA'
     ,'lot_frontage': 69.0
     ,'garage_yr_blt': 1978
     ,'bsmt_half_bath': 0.0
     ,'bsmt_full_bath': 0.0
     ,'garage_area': 0.0
     ,'garage_cars': 0.0
     ,'bsmtfin_sf_1': 368.0
     ,'bsmt_unf_sf': 0.0
     ,'bsmtfin_sf_2': 0.0
     ,'electrical': 'SBrkr'
}
,inplace=True)

In [11]:
kaggle.isna().sum().sum()

0

In [12]:
kaggle.shape

(879, 77)

## Get Dummies

In [13]:
test_kaggle = pd.get_dummies(kaggle)

In [14]:
test_kaggle.shape

(879, 284)

In [15]:
set(cols).difference(test_kaggle.columns)

{'misc_val'}

In [17]:
test_kaggle[cols].head()

,ms_subclass,lot_frontage,lot_area,overall_qual,overall_cond,year_built,year_remod/add,mas_vnr_area,bsmtfin_sf_1,bsmtfin_sf_2,...,garage_qual_NA,garage_qual_TA,garage_cond_NA,garage_cond_TA,paved_drive_N,paved_drive_Y,fence_MnPrv,fence_NA,sale_type_New,sale_type_WD
Id,,,,,,,,,,,,,,,,,,,,,
2658,190,69.0,9142,6,8,1910,1950,0.0,0,0,...,0,0,0,0,0,1,0,1,0,1
2718,90,69.0,9662,5,4,1977,1977,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
2414,60,58.0,17104,7,5,2006,2006,0.0,554,0,...,0,1,0,1,0,1,0,1,1,0
1989,30,60.0,8520,5,6,1923,2006,0.0,0,0,...,0,0,0,1,1,0,0,1,0,1
625,20,69.0,9500,6,5,1963,1963,247.0,609,0,...,0,1,0,1,0,1,0,1,0,1
333,160,21.0,1890,4,6,1972,1972,0.0,294,0,...,0,1,0,1,0,1,0,1,0,1
1327,20,52.0,8516,4,6,1958,2006,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
858,20,69.0,9286,5,7,1977,1989,0.0,196,0,...,0,1,0,1,0,1,0,1,0,1
95,160,39.0,3515,7,5,2004,2004,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
1568,20,75.0,10125,6,6,1977,1977,0.0,641,279,...,0,1,0,1,0,1,1,0,0,1
2482,120,50.0,7175,6,5,1991,1991,0.0,278,0,...,0,1,0,1,0,1,0,1,0,1
1364,30,60.0,7200,6,7,1925,1992,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
2584,20,75.0,11310,6,5,1954,1954,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
818,90,69.0,7976,7,5,2000,2000,23.0,820,0,...,0,1,0,1,0,1,0,1,0,1
2673,70,69.0,11737,6,7,1924,1996,0.0,0,0,...,0,0,0,1,0,1,0,0,0,1
2089,20,60.0,9060,5,6,1957,2006,98.0,0,0,...,0,1,0,1,0,1,1,0,0,1
1297,190,60.0,10800,6,6,1940,1950,0.0,590,0,...,0,1,0,1,0,1,0,1,0,0
790,20,68.0,9571,5,5,1956,1956,0.0,257,0,...,0,1,0,1,0,1,0,0,0,1
2616,20,80.0,10800,6,6,1961,1992,104.0,913,0,...,0,1,0,1,0,1,0,1,0,1
720,70,121.0,17671,8,9,1882,1986,0.0,216,0,...,0,1,0,1,0,0,0,1,0,1
222,20,69.0,8246,5,8,1968,2001,0.0,188,668,...,0,1,0,1,0,1,1,0,0,1
557,20,69.0,8499,5,6,1961,1961,0.0,660,0,...,0,1,0,1,0,1,0,1,0,1
1148,120,50.0,8012,6,5,1993,1994,0.0,165,841,...,0,1,0,1,0,1,0,1,0,1
2766,80,69.0,21453,6,5,1969,1969,0.0,938,0,...,0,1,0,1,0,1,0,1,0,1
534,20,80.0,9605,7,6,2007,2007,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
1452,20,60.0,7180,5,7,1972,1972,0.0,390,0,...,0,1,0,1,0,1,0,1,0,1
630,50,69.0,12513,4,4,1920,2007,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
2648,70,50.0,9000,5,6,1880,1991,0.0,0,0,...,0,0,0,0,1,0,1,0,0,1
125,85,80.0,8800,6,7,1963,1963,156.0,763,0,...,0,1,0,1,0,1,1,0,0,1
1904,50,51.0,3500,3,5,1945,1950,0.0,144,0,...,1,0,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,160,24.0,1733,6,6,1980,1980,0.0,0,0,...,0,1,0,1,0,1,0,0,0,1
2784,80,42.0,10385,6,6,1978,1978,123.0,595,400,...,0,0,0,1,0,1,0,1,0,1
972,120,32.0,4500,6,5,1998,1998,320.0,866,0,...,0,1,0,1,0,1,0,1,0,1
599,20,69.0,9790,6,5,1967,1967,0.0,251,630,...,0,1,0,1,0,1,0,1,0,1
2614,20,60.0,7332,6,6,1959,1959,207.0,414,0,...,0,1,0,1,0,1,0,1,0,1
2582,90,69.0,7032,5,5,1979,1979,0.0,943,0,...,0,1,0,1,0,1,0,1,0,1
1409,50,66.0,21780,6,7,1918,1950,0.0,0,0,...,0,1,0,1,1,0,0,1,0,1
175,50,60.0,5790,3,6,1915,1950,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
352,120,61.0,7380,8,5,1998,1998,0.0,341,0,...,0,1,0,1,0,1,0,1,0,1
976,180,21.0,1526,4,8,1970,2002,0.0,515,0,...,0,1,0,1,0,1,0,1,0,1
2134,60,72.0,11317,7,5,2003,2003,101.0,0,0,...,0,1,0,1,0,1,0,1,0,1
984,20,69.0,8780,5,5,1985,1985,0.0,625,0,...,1,0,1,0,0,1,1,0,0,1
2396,20,90.0,12378,9,5,2003,2004,0.0,1274,0,...,0,1,0,1,0,1,0,1,0,1
1673,120,34.0,4058,7,5,1998,1998,182.0,584,139,...,0,1,0,1,0,1,0,1,0,1
404,160,24.0,2368,5,6,1970,1970,312.0,765,0,...,0,1,0,1,0,1,0,1,0,1
607,20,85.0,9350,5,6,1961,1995,217.0,310,512,...,0,1,0,1,0,1,1,0,0,1
814,90,64.0,7040,5,5,1979,1979,216.0,1094,0,...,0,1,0,1,0,1,0,1,0,1
868,60,70.0,8749,7,5,2002,2002,0.0,0,0,...,0,1,0,1,0,1,0,1,0,1
2271,20,69.0,7777,6,5,1996,1996,203.0,0,0,...,0,1,0,1,0,1,0,1,0,1
1633,160,69.0,5062,7,5,1984,1984,0.0,828,182,...,0,1,0,1,0,1,0,1,0,1
337,90,70.0,7700,5,2,1985,1986,0.0,0,0,...,0,1,0,0,0,1,0,1,0,1
2765,20,69.0,36500,5,5,1964,1964,621.0,812,0,...,0,1,0,1,1,0,0,1,0,1
1746,20,182.0,14572,7,5,2004,2004,0.0,1300,0,...,0,1,0,1,0,1,0,1,0,1
368,20,80.0,11844,8,5,2008,2008,464.0,0,0,...,0,1,0,1,0,1,0,1,1,0
2806,20,70.0,8810,7,5,2003,2003,0.0,1000,0,...,0,1,0,1,0,1,0,1,0,1
1662,60,80.0,8000,6,6,1974,1974,0.0,931,153,...,0,1,0,1,0,1,0,1,0,1
1234,60,90.0,14670,6,7,1966,1999,410.0,575,0,...,0,1,0,1,0,1,1,0,0,1
1373,20,55.0,8250,5,5,1968,1968,0.0,250,492,...,0,1,0,1,0,1,0,1,0,1
1672,20,60.0,9000,4,6,1971,1971,0.0,616,0,...,0,1,0,1,0,1,0,0,0,1
1939,20,70.0,8400,5,5,1955,1955,0.0,793,0,...,0,1,0,1,0,1,0,0,0,1

In [16]:
test_kaggle['misc_val'] = 0

## Scale data

In [18]:
kaggle_sc = ss.transform(test_kaggle[cols])

/Users/davidbickham/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.

## Make predictions

In [19]:
preds = lr.predict(kaggle_sc)

## Align predictions back with index and set up header

In [20]:
submission = pd.DataFrame(preds, index=kaggle.index, columns=['SalePrice'])

## Sort index (required for proper submission)

In [21]:
submission.sort_index(inplace=True)

## Save to csv to submit

In [22]:
submission.to_csv('../data/numeric_only_lr.csv')

## Use command line `head` to check data is correct format

In [23]:
!head ../data/numeric_only_lr.csv

Id,SalePrice
2,106591.47113902813
4,270349.646516478
6,186409.64651647798
7,205740.64651647798
17,187743.64651647798
18,330631.22183108144
22,196276.47113902814
27,114689.47113902813
31,87446.646516478